In [1]:
import torch
torch.__version__

'2.8.0+cu128'

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 3, 3])

In [14]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.1876, 0.3641, 0.5123, 0.6228],
         [0.5796, 0.7829, 0.4642, 0.3401],
         [0.3968, 0.4394, 0.4273, 0.0462]]),
 torch.float32)

In [15]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [16]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [17]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [18]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
float32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None,
                              device=None,
                              requires_grad=False)
float32_tensor.shape, float32_tensor.dtype, float32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [21]:
float16_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=torch.float16)  # Or torch.half
float16_tensor.dtype

torch.float16

In [22]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(some_tensor.shape)
print(some_tensor.dtype)
print(some_tensor.device)

tensor([[0.9469, 0.9951, 0.8867, 0.9656],
        [0.2824, 0.6014, 0.7392, 0.1271],
        [0.1476, 0.3448, 0.1289, 0.4053]])
torch.Size([3, 4])
torch.float32
cpu


In [23]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [24]:
tensor * 10

tensor([10, 20, 30])

In [25]:
tensor - 10

tensor([-9, -8, -7])

In [26]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [27]:
tensor.dtype, (tensor / 10).dtype

(torch.int64, torch.float32)

In [28]:
torch.mul(tensor, 10), torch.add(tensor, 10), tensor

(tensor([10, 20, 30]), tensor([11, 12, 13]), tensor([1, 2, 3]))

In [29]:
tensor * tensor

tensor([1, 4, 9])

In [30]:
torch.matmul(tensor, tensor)

tensor(14)

In [31]:
tensor @ tensor # The same as torch.matmul

tensor(14)

In [32]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 1.45 ms, sys: 888 μs, total: 2.34 ms
Wall time: 1.42 ms


tensor(14)

In [33]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 417 μs, sys: 0 ns, total: 417 μs
Wall time: 319 μs


tensor(14)

In [34]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

In [35]:
# This would produce an error
# tensor_A @ tensor_B

In [36]:
tensor_B, tensor_B.T

(tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]),
 tensor([[ 7.,  8.,  9.],
         [10., 11., 12.]]))

In [37]:
tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [38]:
tensor_A @ tensor_B.T

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [39]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2, out_features=6)
print(f"Weights: {linear.weight}")

x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}")
print(f"Output shape: {output.shape}")
print(f"Output: {output}")

Weights: Parameter containing:
tensor([[ 0.5406,  0.5869],
        [-0.1657,  0.6496],
        [-0.1549,  0.1427],
        [-0.3443,  0.4153],
        [ 0.6233, -0.5188],
        [ 0.6146,  0.1323]], requires_grad=True)
Input shape: torch.Size([3, 2])
Output shape: torch.Size([3, 6])
Output: tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)


In [40]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}")  # .mean() needs the tensor to be a specific datatype (such as float32)
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [42]:
print(f"Index of max value: {x.argmax()}")
print(f"Index of min value: {x.argmin()}")

Index of max value: 9
Index of min value: 0


In [43]:
tensor = torch.arange(10., 100., 10.)
tensor, tensor.dtype

(tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.]), torch.float32)

In [44]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [45]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [46]:
x = torch.arange(1, 8)
x, x.shape, x.dim()

(tensor([1, 2, 3, 4, 5, 6, 7]), torch.Size([7]), 1)

In [47]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7]]), torch.Size([1, 7]))

In [48]:
z = x.view(1, 7)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7]]), torch.Size([1, 7]))

In [49]:
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7]]), tensor([5, 2, 3, 4, 5, 6, 7]))

In [50]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7],
        [5, 2, 3, 4, 5, 6, 7],
        [5, 2, 3, 4, 5, 6, 7],
        [5, 2, 3, 4, 5, 6, 7]])

In [51]:
x_squeezed = x_reshaped.squeeze()
x_reshaped, x_squeezed

(tensor([[5, 2, 3, 4, 5, 6, 7]]), tensor([5, 2, 3, 4, 5, 6, 7]))

In [52]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[5, 2, 3, 4, 5, 6, 7]])

In [53]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)

x_original, x_original.shape, x_permuted, x_permuted.shape

(tensor([[[0.2666, 0.6274, 0.2696],
          [0.4414, 0.2969, 0.8317],
          [0.1053, 0.2695, 0.3588],
          ...,
          [0.5697, 0.2088, 0.6539],
          [0.3397, 0.9565, 0.0660],
          [0.3421, 0.0172, 0.3031]],
 
         [[0.6576, 0.9813, 0.5840],
          [0.9902, 0.5978, 0.7888],
          [0.9008, 0.9180, 0.2201],
          ...,
          [0.5322, 0.8510, 0.4556],
          [0.1844, 0.8533, 0.5698],
          [0.3568, 0.1704, 0.6172]],
 
         [[0.0231, 0.6317, 0.7472],
          [0.0614, 0.1727, 0.1405],
          [0.9203, 0.9251, 0.5313],
          ...,
          [0.4989, 0.0933, 0.3064],
          [0.6272, 0.5955, 0.8636],
          [0.8345, 0.2273, 0.2865]],
 
         ...,
 
         [[0.3599, 0.1989, 0.5711],
          [0.5387, 0.1378, 0.9763],
          [0.5521, 0.6004, 0.1658],
          ...,
          [0.1790, 0.9954, 0.6617],
          [0.9871, 0.5877, 0.7375],
          [0.1551, 0.7881, 0.3759]],
 
         [[0.7442, 0.8621, 0.7548],
          [0

In [54]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [55]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [56]:
x[0][0]

tensor([1, 2, 3])

In [57]:
x[0][0][2]

tensor(3)

In [58]:
x[:, 0]

tensor([[1, 2, 3]])

In [59]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [60]:
x[:, 1, 1]

tensor([5])

In [61]:
x[0, 0, :]  # Same as x[0][0]

tensor([1, 2, 3])

In [62]:
import numpy as np

array = np.arange(1.0, 8.0)
array

array([1., 2., 3., 4., 5., 6., 7.])

In [63]:
tensor = torch.from_numpy(array)
tensor  # numpy arrays are float64 by default, so tensor will also be float64

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [64]:
converted_tensor = tensor.type(torch.float32)
converted_tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

In [65]:
array = array + 1
tensor  # It doesn't change

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [66]:
tensor = torch.ones(7)
array = tensor.numpy()
tensor, array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [67]:
tensor = tensor + 1
tensor, array

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [68]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

random_tensor_A, random_tensor_B, random_tensor_A == random_tensor_B

(tensor([[0.8016, 0.3649, 0.6286, 0.9663],
         [0.7687, 0.4566, 0.5745, 0.9200],
         [0.3230, 0.8613, 0.0919, 0.3102]]),
 tensor([[0.9536, 0.6002, 0.0351, 0.6826],
         [0.3743, 0.5220, 0.1336, 0.9666],
         [0.9754, 0.8474, 0.8988, 0.1105]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [69]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_A = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)

random_tensor_B = torch.rand(3, 4)

random_tensor_A, random_tensor_B, random_tensor_A == random_tensor_B

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [70]:
torch.cuda.is_available()

True

In [71]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [72]:
torch.cuda.device_count()

1

In [73]:
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [74]:
# We can't do this, the tensor must first be copied to the cpu
# tensor_gpu.numpy()
tensor_cpu = tensor_gpu.cpu()
tensor_cpu, tensor_cpu.numpy()

(tensor([1, 2, 3]), array([1, 2, 3]))