In [56]:
import torch
import numpy as np

In [57]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
data, x_data

([[1, 2], [3, 4]],
 tensor([[1, 2],
         [3, 4]]))

In [58]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
np_array, x_np

(array([[1, 2],
        [3, 4]]),
 tensor([[1, 2],
         [3, 4]]))

In [59]:
x_ones = torch.ones_like(x_data)
print(f"Ones tensor:\n{x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random tensor:\n{x_rand}\n")

Ones tensor:
tensor([[1, 1],
        [1, 1]])

Random tensor:
tensor([[0.1251, 0.2593],
        [0.0532, 0.0403]])



In [60]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

rand_tensor, ones_tensor, zeros_tensor

(tensor([[0.3593, 0.9961, 0.0939],
         [0.0689, 0.4133, 0.9287]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [61]:
tensor = torch.rand(3, 4)

tensor.shape, tensor.dtype, tensor.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

In [62]:
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

tensor

tensor([[0.9071, 0.2105, 0.4112, 0.1291],
        [0.0121, 0.7707, 0.0275, 0.4510],
        [0.5543, 0.4984, 0.5852, 0.9835]], device='cuda:0')

In [63]:
tensor = torch.rand(4, 4)
print(tensor)

print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")  # : and ... can be exchanged in this case
print(f"Last column: {tensor[:, -1]}")  # : and ... can be exchanged in this case
# ... is like adding a : for every dimension (ex: tensor[:, -1] could be tensor[:, :, :, -1]
# if the tensor had that many dimensions)

tensor[:, 1] = 0
tensor

tensor([[0.9458, 0.9800, 0.1955, 0.6886],
        [0.5415, 0.2576, 0.6847, 0.6808],
        [0.0360, 0.1543, 0.5688, 0.5927],
        [0.3653, 0.2145, 0.8997, 0.8554]])
First row: tensor([0.9458, 0.9800, 0.1955, 0.6886])
First column: tensor([0.9458, 0.5415, 0.0360, 0.3653])
Last column: tensor([0.6886, 0.6808, 0.5927, 0.8554])


tensor([[0.9458, 0.0000, 0.1955, 0.6886],
        [0.5415, 0.0000, 0.6847, 0.6808],
        [0.0360, 0.0000, 0.5688, 0.5927],
        [0.3653, 0.0000, 0.8997, 0.8554]])

In [64]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
print(tensor)

t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [65]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print(y3)

# Element-wise product
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(z3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [66]:
agg = tensor.sum()
agg_item = agg.item()
agg_item, type(agg_item)

(12.0, float)

In [67]:
print(f"{tensor}\n")
tensor.add_(5)  # _ means the operation is made in-place
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])



tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [68]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [69]:
t.add_(1)
t, n

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [70]:
n = np.ones(5)
t = torch.from_numpy(n)
n, t

(array([1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64))

In [71]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
