In [5]:
import torch
torch.__version__

'2.8.0+cu128'

In [8]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [10]:
scalar.item()

7

In [11]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [25]:
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [26]:
matrix.ndim

2

In [28]:
matrix.shape

torch.Size([2, 2])

In [30]:
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [32]:
tensor.ndim

3

In [34]:
tensor.shape

torch.Size([1, 3, 3])

In [35]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.6809, 0.7370, 0.4888, 0.6568],
         [0.6056, 0.2701, 0.4440, 0.5473],
         [0.2276, 0.0134, 0.1544, 0.6550]]),
 torch.float32)

In [36]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [39]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [40]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [42]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
float32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None,
                              device=None,
                              requires_grad=False)
float32_tensor.shape, float32_tensor.dtype, float32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [51]:
float16_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=torch.float16)  # Or torch.half
float16_tensor.dtype

torch.float16