In [99]:
import torch
torch.__version__

'2.8.0+cu128'

In [100]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [101]:
scalar.ndim

0

In [102]:
scalar.item()

7

In [103]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [104]:
vector.ndim

1

In [105]:
vector.shape

torch.Size([2])

In [106]:
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [107]:
matrix.ndim

2

In [108]:
matrix.shape

torch.Size([2, 2])

In [109]:
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [110]:
tensor.ndim

3

In [111]:
tensor.shape

torch.Size([1, 3, 3])

In [112]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.2666, 0.6274, 0.2696, 0.4414],
         [0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062]]),
 torch.float32)

In [113]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [114]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [115]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [116]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [118]:
float32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None,
                              device=None,
                              requires_grad=False)
float32_tensor.shape, float32_tensor.dtype, float32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [119]:
float16_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=torch.float16)  # Or torch.half
float16_tensor.dtype

torch.float16

In [120]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(some_tensor.shape)
print(some_tensor.dtype)
print(some_tensor.device)

tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])
torch.Size([3, 4])
torch.float32
cpu


In [121]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [122]:
tensor * 10

tensor([10, 20, 30])

In [123]:
tensor - 10

tensor([-9, -8, -7])

In [124]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [125]:
tensor.dtype, (tensor / 10).dtype

(torch.int64, torch.float32)

In [126]:
torch.mul(tensor, 10), torch.add(tensor, 10), tensor

(tensor([10, 20, 30]), tensor([11, 12, 13]), tensor([1, 2, 3]))

In [127]:
tensor * tensor

tensor([1, 4, 9])

In [128]:
torch.matmul(tensor, tensor)

tensor(14)

In [129]:
tensor @ tensor # The same as torch.matmul

tensor(14)

In [130]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 120 μs, sys: 18 μs, total: 138 μs
Wall time: 179 μs


tensor(14)

In [131]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 42 μs, sys: 6 μs, total: 48 μs
Wall time: 65.8 μs


tensor(14)

In [132]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

In [133]:
# This will produce an error
tensor_A @ tensor_B

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_B, tensor_B.T

(tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]),
 tensor([[ 7.,  8.,  9.],
         [10., 11., 12.]]))

In [ ]:
tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [ ]:
tensor_A @ tensor_B.T

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2, out_features=6)
print(f"Weights: {linear.weight}")

x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}")
print(f"Output shape: {output.shape}")
print(f"Output: {output}")

Weights: Parameter containing:
tensor([[ 0.5406,  0.5869],
        [-0.1657,  0.6496],
        [-0.1549,  0.1427],
        [-0.3443,  0.4153],
        [ 0.6233, -0.5188],
        [ 0.6146,  0.1323]], requires_grad=True)
Input shape: torch.Size([3, 2])
Output shape: torch.Size([3, 6])
Output: tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)


In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}")  # .mean() needs the tensor to be a specific datatype (such as float32)
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [ ]:
print(f"Index of max value: {x.argmax()}")
print(f"Index of min value: {x.argmin()}")

Index of max value: 9
Index of min value: 0


In [ ]:
tensor = torch.arange(10., 100., 10.)
tensor, tensor.dtype

(tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.]), torch.float32)

In [ ]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [ ]:
x = torch.arange(1, 8)
x, x.shape, x.dim()

(tensor([1, 2, 3, 4, 5, 6, 7]), torch.Size([7]), 1)

In [ ]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7]]), torch.Size([1, 7]))

In [ ]:
z = x.view(1, 7)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7]]), torch.Size([1, 7]))

In [ ]:
z[:, 0] = 5